spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iterview?serverTimeZone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.example.iterview.model
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
